name: Duel
version: '${version}'
main: com.seniorcluckers.duel.Duel
api-version: 1.19
authors: [ SeniorCluckers, Insprill ]
description: A duel plugin.
commands:
  duel:
    description: "Main command for duel plugin."